name: sombra-cli Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  GO_VERSION: '1.26'
  PY_VERSION: '3.13'

jobs:
  build-cli:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, windows, darwin ]
        goarch: [ "386", amd64, arm64 ]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
        include:
          - goos: darwin
            os: macos-latest
          - goos: linux
            os: ubuntu-latest
          - goos: windows
            os: windows-latest
            suffix: .exe
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: go mod tidy

      - name: Build CLI
        run: make build WHAT=sombra

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sombra-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/sombra*

  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PY_VERSION }}

      - name: Build docs
        run: make build-docs

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  release:
    runs-on: ubuntu-latest
    needs: [ build-cli, build-docs ]
    permissions:
      contents: write
    steps:
      - name: Download CLI artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release-artifacts
          pattern: sombra-*
          merge-multiple: true

      - name: Release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-artifacts/*

  docs:
    runs-on: ubuntu-latest
    needs: [ release ]
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
